import { CSSProperties } from "react";

export const companyStyles: Record<string, CSSProperties> = {
  page: {
    backgroundColor: "#f3f4f6",
    minHeight: "100vh",
  },
  header: {
    padding: "20px 40px",
    backgroundColor: "#fff",
    borderBottom: "1px solid #e5e7eb",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: { margin: 0 },
  headerSubtitle: { fontSize: 12, color: "#6b7280" },
  userBox: { display: "flex", gap: 10, alignItems: "center" },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    backgroundColor: "#6366f1",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 600,
  },
  userName: { fontWeight: 600 },
  userRole: { fontSize: 12, color: "#6b7280" },
  container: {
    display: "grid",
    // gridTemplateColumns: "2fr 1fr",
    gap: 10,
    padding: 5,
  },
  companyCard: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 12,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    boxShadow: "0 4px 12px rgba(0,0,0,0.05)",
  },
  companyInfo: { display: "flex", gap: 20, alignItems: "center" },
  companyLogo: { backgroundColor: "#eef2ff", padding: 10, borderRadius: 12 },
  placeholderLogo: {
    width: 60,
    height: 60,
    backgroundColor: "#6366f1",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 24,
    fontWeight: 600,
    borderRadius: 12,
  },
  companyName: { margin: 0, display: "flex", alignItems: "center", gap: 10 },
  statusBadge: {
    fontSize: 12,
    padding: "2px 8px",
    borderRadius: 999,
  },
  activeBadge: {
    backgroundColor: "#d1fae5",
    color: "#065f46",
  },
  suspendedBadge: {
    backgroundColor: "#fee2e2",
    color: "#b91c1c",
  },
  inactiveBadge: {
    backgroundColor: "#e5e7eb",
    color: "#374151",
  },
  companyMeta: { margin: 0, fontSize: 13, color: "#6b7280" },
  actions: { display: "flex", gap: 10, alignItems: "center" },
  editBtn: {
    padding: "8px 14px",
    borderRadius: 8,
    border: "1px solid #d1d5db",
    backgroundColor: "#fff",
    cursor: "pointer",
  },
  suspendBtn: {
    padding: "8px 14px",
    borderRadius: 8,
    border: "1px solid #fecaca",
    backgroundColor: "#fee2e2",
    color: "#b91c1c",
    cursor: "pointer",
  },
  confirmBox: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    backgroundColor: "#fff3f3",
    padding: "4px 8px",
    borderRadius: 6,
  },
  confirmYes: {
    background: "#b91c1c",
    color: "#fff",
    border: "none",
    padding: "4px 10px",
    borderRadius: 4,
    cursor: "pointer",
  },
  confirmNo: {
    background: "#e5e7eb",
    border: "none",
    padding: "4px 10px",
    borderRadius: 4,
    cursor: "pointer",
  },
  card: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 12,
    boxShadow: "0 4px 12px rgba(0,0,0,0.05)",
  },
  tabs: { display: "flex", gap: 20, marginBottom: 20, cursor: "pointer" },
  activeTab: {
    fontWeight: 600,
    color: "#4f46e5",
    borderBottom: "2px solid #4f46e5",
    paddingBottom: 4,
  },
  tab: { color: "#6b7280", paddingBottom: 4 },
  sectionTitle: {
    fontSize: 13,
    color: "#9ca3af",
    marginTop: 16,
    marginBottom: 8,
  },
  UserGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 },
  UserCard: {
    border: "1px solid #e5e7eb",
    padding: 14,
    borderRadius: 10,
    display: "flex",
    gap: 12,
    alignItems: "center",
  },
  UserAvatar: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    backgroundColor: "#e0e7ff",
    color: "#3730a3",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 600,
  },
  UserName: { fontWeight: 500 },
  UserEmail: { fontSize: 12, color: "#6b7280" },
  emptyText: { color: "#9ca3af", fontSize: 14, fontStyle: "italic" },
  tabContent: { padding: "20px 0", textAlign: "center", color: "#6b7280" },
  summaryTitle: { fontSize: 13, color: "#9ca3af", marginBottom: 10 },
  revenue: { marginBottom: 20 },
  revenueLabel: { fontSize: 14, color: "#4b5563" },
  revenueAmount: { fontSize: 22, fontWeight: 700, margin: "4px 0" },
  revenueGrowth: { fontSize: 12 },
  statsRow: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  statValue: { fontSize: 18, fontWeight: 600 },
  statLabel: { fontSize: 12, color: "#6b7280" },
  primaryButton: {
    width: "100%",
    padding: "10px",
    backgroundColor: "#6366f1",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    marginTop: 8,
  },
  auditList: { listStyle: "none", padding: 0, margin: 0 },
  auditItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 0",
    borderBottom: "1px solid #e5e7eb",
    fontSize: 14,
  },
  auditTime: { color: "#9ca3af", fontSize: 12 },
  viewAllLink: {
    background: "none",
    border: "none",
    color: "#4f46e5",
    cursor: "pointer",
    fontSize: 14,
    marginTop: 12,
    textAlign: "left",
    padding: 0,
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
  },
  loadingSpinner: {
    border: "4px solid #e5e7eb",
    borderTop: "4px solid #6366f1",
    borderRadius: "50%",
    width: 40,
    height: 40,
    animation: "spin 1s linear infinite",
  },
  errorContainer: {
    padding: 40,
    textAlign: "center",
  },
};
