import { CSSProperties } from "react";

const HEADER_HEIGHT = 58;

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#f9fafb",
    position: "relative",
    fontFamily: "Inter, system-ui, sans-serif",
  },
  header: {
    padding: "16px 40px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderBottom: "1px solid #e5e7eb",
    boxShadow: "0 2px 4px rgba(0,0,0,0.02)",
    position: "fixed",
    height: HEADER_HEIGHT,
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  logoContainer: {
    display: "flex",
    gap: 10,
    alignItems: "center",
  },
  logoBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: "#2563eb",
    color: "#fff",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontWeight: "bold",
    fontSize: 18,
  },
  logoText: {
    fontWeight: 600,
    fontSize: 16,
  },
  searchInput: {
    padding: "8px 14px",
    borderRadius: 8,
    border: "1px solid #d1d5db",
    width: 480,
    fontSize: 14,
    outline: "none",
    transition: "border 0.2s",
  },
  headerRight: {
    display: "flex",
    gap: 16,
    alignItems: "center",
  },
  notificationIcon: {
    fontSize: 20,
    cursor: "pointer",
  },
  logout: {
    padding: "6px 14px",
    background: "#ef4444",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    fontWeight: 500,
    fontSize: 14,
  },
  body: {
    display: "flex",
  },
  sidebar: {
    width: 200,
    height: `calc(100vh - ${HEADER_HEIGHT}px)`,
    padding: "24px 16px",
    backgroundColor: "#ffffff",
    borderRight: "1px solid #e5e7eb",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    position: "fixed",
    top: HEADER_HEIGHT,
    left: 0,
    overflow: "hidden",
    zIndex: 999,
  },
  sidebarTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: "#9ca3af",
    marginBottom: 12,
    letterSpacing: "0.5px",
  },
  sidebarItem: {
    display: "block",
    width: "100%",
    padding: "10px 12px",
    background: "none",
    border: "none",
    textAlign: "left",
    cursor: "pointer",
    borderRadius: 6,
    fontSize: 14,
    color: "#374151",
    marginBottom: 4,
  },
  sidebarActive: {
    display: "block",
    width: "100%",
    padding: "10px 12px",
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    textAlign: "left",
    fontWeight: 500,
    fontSize: 14,
    marginBottom: 4,
  },
  userBox: {
    borderTop: "1px solid #e5e7eb",
    paddingTop: 16,
    marginTop: 16,
  },
  main: {
    marginTop: HEADER_HEIGHT,
    marginLeft: 200,
    minHeight: `calc(100vh - ${HEADER_HEIGHT}px)`,
    flex: 1,
    padding: "32px 40px",
  },
  mainHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  subtitle: {
    color: "#6b7280",
    fontSize: 14,
    marginTop: 4,
  },
  primaryButton: {
    padding: "10px 18px",
    backgroundColor: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    fontWeight: 500,
    fontSize: 14,
    cursor: "pointer",
    transition: "background 0.2s",
  },
  metricsRow: {
    display: "flex",
    gap: 20,
    marginBottom: 32,
  },
  metricCard: {
    backgroundColor: "#ffffff",
    padding: "20px 24px",
    borderRadius: 12,
    flex: 1,
    boxShadow: "0 4px 12px rgba(0,0,0,0.03)",
    border: "1px solid #f0f2f5",
  },
  metricTitle: {
    fontSize: 14,
    color: "#6b7280",
    marginBottom: 8,
  },
  tableCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: "24px",
    boxShadow: "0 8px 20px rgba(0,0,0,0.02)",
    border: "1px solid #f0f2f5",
  },
  tableHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  tableCount: {
    fontSize: 14,
    color: "#6b7280",
    backgroundColor: "#f3f4f6",
    padding: "4px 10px",
    borderRadius: 20,
  },
  table: {
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: "0 8px",
  },
  th: {
    textAlign: "left",
    padding: "12px 16px",
    fontSize: 13,
    fontWeight: 600,
    color: "#6b7280",
    borderBottom: "1px solid #e5e7eb",
  },
  tr: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    transition: "background 0.2s, box-shadow 0.2s",
    boxShadow: "0 2px 4px rgba(0,0,0,0.02)",
  },
  td: {
    padding: "16px",
    fontSize: 14,
    borderBottom: "1px solid #f3f4f6",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 12px",
    borderRadius: 30,
    fontSize: 12,
    fontWeight: 500,
  },
  manageButton: {
    padding: "6px 14px",
    borderRadius: 20,
    border: "1px solid #2563eb",
    background: "none",
    color: "#2563eb",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    transition: "all 0.2s",
  },
  noResults: {
    padding: "40px",
    textAlign: "center",
    color: "#9ca3af",
    fontSize: 14,
  },
  errorBanner: {
    backgroundColor: "#fee2e2",
    color: "#b91c1c",
    padding: "12px 20px",
    borderRadius: 8,
    marginBottom: 20,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    border: "1px solid #fecaca",
  },
  errorClose: {
    background: "none",
    border: "none",
    fontSize: 20,
    cursor: "pointer",
    color: "#b91c1c",
    padding: "0 8px",
  },
  loading: {
    padding: "40px",
    textAlign: "center",
    color: "#6b7280",
    fontSize: 14,
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
  },
  modal: {
    backgroundColor: "#fff",
    padding: "24px",
    borderRadius: 12,
    width: "400px",
    maxWidth: "90%",
    boxShadow: "0 20px 25px -5px rgba(0,0,0,0.1)",
  },
  modalInput: {
    width: "100%",
    padding: "10px 12px",
    border: "1px solid #d1d5db",
    borderRadius: 6,
    fontSize: 14,
    marginBottom: 20,
    outline: "none",
  },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 12,
  },
  modalCancel: {
    padding: "8px 16px",
    background: "none",
    border: "1px solid #d1d5db",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 14,
  },
  modalCreate: {
    padding: "8px 16px",
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 14,
  },
};
