import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#f0f2f5",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  container: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "120px",
    padding: "40px",
  },
  left: {
    maxWidth: 500,
  },
  brandBox: {
    width: 160,
    height: 160,
    borderRadius: 14,
    backgroundColor: "#1877f2",
    color: "#fff",
    fontSize: 36,
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    marginLeft: "auto",
    marginRight: "auto",
  },
  brandTitle: {
    fontSize: 42,
    fontWeight: 700,
    margin: 0,
    color: "#1c1e21",
  },
  brandSubtitle: {
    fontSize: 20,
    color: "#606770",
    marginTop: 16,
  },
  right: {
    width: 400,
  },
  card: {
    backgroundColor: "#ffffff",
    padding: 24,
    borderRadius: 10,
    boxShadow: "0 8px 24px rgba(0,0,0,0.1)",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  passwordWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  input: {
    padding: "14px",
    paddingRight: "44px", // espacio para el botón
    borderRadius: 6,
    border: "1px solid #dddfe2",
    fontSize: 16,
    width: "100%",
    boxSizing: "border-box",
  },
  showButton: {
    position: "absolute",
    right: 10,
    background: "none",
    border: "none",
    color: "#606770",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
    borderRadius: 4,
    transition: "background 0.2s",
  },
  loginButton: {
    marginTop: 4,
    padding: "14px",
    backgroundColor: "#1877f2",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
  },
  divider: {
    height: 1,
    backgroundColor: "#dadde1",
    margin: "10px 0",
  },
  registerButton: {
    padding: "14px",
    backgroundColor: "#42b72a",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
  },
  error: {
    backgroundColor: "#fee2e2",
    color: "#b91c1c",
    padding: "10px",
    borderRadius: 6,
    fontSize: 14,
    textAlign: "center",
    border: "1px solid #fecaca",
  },
  footer: {
    padding: 20,
    textAlign: "center",
    fontSize: 12,
    color: "#8a8d91",
  },
  footerLink: {
    margin: "0 8px",
    cursor: "pointer",
  },
};
